#pragma once

struct PokedexEntry
{
    /*0x00*/ u8 categoryName[12];
    /*0x0C*/ u16 height; //in decimeters
    /*0x0E*/ u16 weight; //in hectograms
    /*0x10*/ const u8* description;
    /*0x14*/ const u8* unusedDescription;
    /*0x18*/ u16 unused;
    /*0x1A*/ u16 pokemonScale;
    /*0x1C*/ u16 pokemonOffset;
    /*0x1E*/ u16 trainerScale;
    /*0x20*/ u16 trainerOffset;
	/*0x22*/ u16 unused2;
};  /*size = 0x24*/

struct ListMenuItem
{
    const u8* name;
    s32 id;
};

struct PokedexScreenData
{
    u8 taskId;
    u8 state;
    u8 data[4];
    u32 unlockedCategories;
    u32 modeSelectInput;
    u16 modeSelectItemsAbove;
    u16 modeSelectCursorPos;
    u8 modeSelectWindowId;
    u8 selectionIconWindowId;
    u8 dexCountsWindowId;
    u8 modeSelectListMenuId;
    u16 pageSpecies[4];
    u8 categoryMonWindowIds[4];
    u8 categoryMonInfoWindowIds[4];
    u8 category;
    u8 firstPageInCategory;
    u8 lastPageInCategory;
    u8 pageNum;
    u8 numMonsOnPage;
    u8 categoryCursorPosInPage;
    u8 categoryPageSelectionCursorTimer;
    u8 parentOfCategoryMenu;
    u32 characteristicMenuInput;
    u16 kantoOrderMenuItemsAbove;
    u16 kantoOrderMenuCursorPos;
    u16 characteristicOrderMenuItemsAbove;
    u16 characteristicOrderMenuCursorPos;
    u16 nationalOrderMenuItemsAbove;
    u16 nationalOrderMenuCursorPos;
    u8 numericalOrderWindowId;
    u8 orderedListMenuTaskId;
    u8 dexOrderId;
    struct ListMenuItem * listItems;
    u16 orderedDexCount;
    u8 windowIds[0x10];
    u16 dexSpecies;
    u16 * bgBufsMem;
    u8 scrollArrowsTaskId;
    u8 categoryPageCursorTaskId;
    u16 modeSelectCursorPosBak;
    u8 unlockedSeviiAreas;
    u16 numSeenKanto;
    u16 numOwnedKanto;
    u16 numSeenNational;
    u16 numOwnedNational;
};

extern struct PokedexScreenData* sPokedexScreenData;

enum
{
    FLAG_GET_SEEN,
    FLAG_GET_CAUGHT,
    FLAG_SET_SEEN,
    FLAG_SET_CAUGHT
};

//Kanto
#define NATIONAL_DEX_NONE 0
#define NATIONAL_DEX_BULBORBLARVA 1
#define NATIONAL_DEX_BULBORB 2
#define NATIONAL_DEX_JUMBOBULBORB 3
#define NATIONAL_DEX_FIERYBLOWLET 4
#define NATIONAL_DEX_FIERYBLOWHOG 5
#define NATIONAL_DEX_TITANBLOWHOG 6
#define NATIONAL_DEX_WOLPOLE 7
#define NATIONAL_DEX_YELLOWWOLLYHOP 8
#define NATIONAL_DEX_MASTERHOP 9
#define NATIONAL_DEX_FLINTBEETLE 10
#define NATIONAL_DEX_DOODLEBUG 11
#define NATIONAL_DEX_GLINTBEETLE 12
#define NATIONAL_DEX_SWOOPINGSNITCHBUG 13
#define NATIONAL_DEX_BUMBLINGSNITCHBUG 14
#define NATIONAL_DEX_DIRIGIBUG 15
#define NATIONAL_DEX_SNOWBULBORB 16
#define NATIONAL_DEX_DWARFFROSTYBULBORB 17
#define NATIONAL_DEX_FROSTYBULBORB 18
#define NATIONAL_DEX_CRUMBUG 19
#define NATIONAL_DEX_BREADBUG 20
#define NATIONAL_DEX_GIANTBREADBUG 21
#define NATIONAL_DEX_EMPERORBULBLAX 22
#define NATIONAL_DEX_SOVREIGNBULBLAX 23
#define NATIONAL_DEX_DWARFBULBEAR 24
#define NATIONAL_DEX_SPOTTYBULBEAR 25
#define NATIONAL_DEX_HONEYWISP 26
#define NATIONAL_DEX_DANDELFLY 27
#define NATIONAL_DEX_DOWNYSNAGRET 28
#define NATIONAL_DEX_BURROWINGSNAGRET 29
#define NATIONAL_DEX_PILEATEDSNAGRET 30
#define NATIONAL_DEX_FEMALESHEARGRUB 31
#define NATIONAL_DEX_SWARMINGSHEARGRUB 32
#define NATIONAL_DEX_MAMASHEARGRUB 33
#define NATIONAL_DEX_MALESHEARGRUB 34
#define NATIONAL_DEX_SHEARWIG 35
#define NATIONAL_DEX_QUEENSHEARWIG 36
#define NATIONAL_DEX_ARISTOCRABOFFSPRING 37
#define NATIONAL_DEX_ARISTOCRAB 38
#define NATIONAL_DEX_GOOLIX 39
#define NATIONAL_DEX_FOOLIX 40
#define NATIONAL_DEX_ARCTICCANNONLARVA 41
#define NATIONAL_DEX_ARCTICCANNONBEETLE 42
#define NATIONAL_DEX_SKITTERLEAF 43
#define NATIONAL_DEX_DESICCATEDSKITTERLEAF 44
#define NATIONAL_DEX_ARMOREDCANNONLARVA 45
#define NATIONAL_DEX_ARMOREDCANNONBEETLE 46
#define NATIONAL_DEX_HORNEDCANNONBEETLE 47
#define NATIONAL_DEX_CREEPINGCHRYSANTHEMUM 48
#define NATIONAL_DEX_STARTLESPORE 49
#define NATIONAL_DEX_HERMITCRAWMAD 50
#define NATIONAL_DEX_BUGEYEDCRAWMAD 51
#define NATIONAL_DEX_DWARFBULBORB 52
#define NATIONAL_DEX_DWARFORANGEBULBORB 53
#define NATIONAL_DEX_BEADYLONGLEGS 54
#define NATIONAL_DEX_RAGINGLONGLEGS 55
#define NATIONAL_DEX_BALDYLONGLEGS 56
#define NATIONAL_DEX_SHAGGYLONGLEGS 57
#define NATIONAL_DEX_BULBMIN 58
#define NATIONAL_DEX_ADULTBULBMIN 59
#define NATIONAL_DEX_SCORNET 60
#define NATIONAL_DEX_SCORNETMAESTRO 61
#define NATIONAL_DEX_BURROWNIT 62
#define NATIONAL_DEX_JOUSTMITE 63
#define NATIONAL_DEX_FLIGHTYJOUSTMITE 64
#define NATIONAL_DEX_VOLATILEDWEEVIL 65
#define NATIONAL_DEX_MANATLEGS 66
#define NATIONAL_DEX_SKUTTERCHUCK 67
#define NATIONAL_DEX_CALCIFIEDCRUSHBLAT 68
#define NATIONAL_DEX_ARACHNODE 69
#define NATIONAL_DEX_MOLDYDWARFBULBORB 70
#define NATIONAL_DEX_MOLDYSLOOCH 71
#define NATIONAL_DEX_TOXSTOOL 72
#define NATIONAL_DEX_PHOSBAT 73
#define NATIONAL_DEX_VEHEAMOTHPHOSBAT 74
#define NATIONAL_DEX_PUCKERINGBLINNOW 75
#define NATIONAL_DEX_SPUTTLEFISH 76
#define NATIONAL_DEX_PRICKLEPUFF 77
#define NATIONAL_DEX_UJADANI 78
#define NATIONAL_DEX_MITITE 79
#define NATIONAL_DEX_WITHERINGBLOWHOG 80
#define NATIONAL_DEX_PUFFYBLOWHOG 81
#define NATIONAL_DEX_ICYBLOWHOG 82
#define NATIONAL_DEX_WHISKERPILLAR 83
#define NATIONAL_DEX_PYROCLASTICSLOOCH 84
#define NATIONAL_DEX_LESSERSPOTTEDJELLYFLOAT 85
#define NATIONAL_DEX_GREATERSPOTTEDJELLYFLOAT 86
#define NATIONAL_DEX_TOADYBLOYSTER 87
#define NATIONAL_DEX_RANGINGBLOYSTER 88
#define NATIONAL_DEX_SNOWYBLOWHOG 89
#define NATIONAL_DEX_BLIZZARDINGBLOWHOG 90
#define NATIONAL_DEX_GILDEMANDWEE 91
#define NATIONAL_DEX_GILDEMANDER 92
#define NATIONAL_DEX_WADDLEQUAFF 93
#define NATIONAL_DEX_GRUBCHUCKER 94
#define NATIONAL_DEX_PEARLYCLAMCLAMP 95
#define NATIONAL_DEX_SUNQUISH 96
#define NATIONAL_DEX_PROQUILLION 97
#define NATIONAL_DEX_TUSKEDBLOWHOG 98
#define NATIONAL_DEX_SNOWFLAKEFLUTTERTAIL 99
#define NATIONAL_DEX_BOGSWALLOW 100
#define NATIONAL_DEX_PUFFMIN 101
#define NATIONAL_DEX_WOLLYHOP 102
#define NATIONAL_DEX_CHILLYHOP 103
#define NATIONAL_DEX_BLOOMCAPBLOYSTER 104
#define NATIONAL_DEX_SCORCHCAKE 105
#define NATIONAL_DEX_WATERDUMPLE 106
#define NATIONAL_DEX_LONGWATERDUMPLE 107
#define NATIONAL_DEX_MOCKIWI 108
#define NATIONAL_DEX_CRESTEDMOCKIWI 109
#define NATIONAL_DEX_ELONGATEDCRUSHBLAT 110
#define NATIONAL_DEX_PUFFSTALK 111
#define NATIONAL_DEX_PUFFSTOOL 112
#define NATIONAL_DEX_ANODEBEETLE 113
#define NATIONAL_DEX_EMPRESSBULBLAX 114
#define NATIONAL_DEX_SKEETERSKATE 115
#define NATIONAL_DEX_MUCKERSKATE 116
#define NATIONAL_DEX_GROOVYLONGLEGS 117
#define NATIONAL_DEX_CRUSTEDRUMPUP 118
#define NATIONAL_DEX_BEARDEDAMPRAT 119
#define NATIONAL_DEX_FIERYBULBLAX 120
#define NATIONAL_DEX_GATTLINGGROINK 121
#define NATIONAL_DEX_ARMURK 122
#define NATIONAL_DEX_SEGMENTEDCRAWBSTER 123
#define NATIONAL_DEX_ARMOREDMAWDAD 124
#define NATIONAL_DEX_SANDBELCHINGMEERSLUG 125
#define NATIONAL_DEX_CLICKINGSLURKER 126
#define NATIONAL_DEX_LURINGSLURKER 127
#define NATIONAL_DEX_MEDUSALSLURKER 128
#define NATIONAL_DEX_PELLETPOSY 129
#define NATIONAL_DEX_MASTERONION 130
#define NATIONAL_DEX_OATCHI 131
#define NATIONAL_DEX_QUAGGLEDMIRECLOPS 132
#define NATIONAL_DEX_ALBINODWARFBULBORB 133
#define NATIONAL_DEX_HAIRYBULBORB 134
#define NATIONAL_DEX_WHIPTONGUEBULBORB 135
#define NATIONAL_DEX_ORANGEBULBORB 136
#define NATIONAL_DEX_WHITEPIKMIN 137
#define NATIONAL_DEX_BLUEPIKMIN 138
#define NATIONAL_DEX_ROCKPIKMIN 139
#define NATIONAL_DEX_YELLOWPIKMIN 140
#define NATIONAL_DEX_WINGEDPIKMIN 141
#define NATIONAL_DEX_REDPIKMIN 142
#define NATIONAL_DEX_PURPLEPIKMIN 143
#define NATIONAL_DEX_WATERWRAITH 144
#define NATIONAL_DEX_TITANDWEEVIL 145
#define NATIONAL_DEX_PLASMWRAITH 146
#define NATIONAL_DEX_ICEPIKMIN 147
#define NATIONAL_DEX_GLOWSEED 148
#define NATIONAL_DEX_GLOWPIKMIN 149
#define NATIONAL_DEX_SMOKYPROGG 150
#define NATIONAL_DEX_MAMUTA 151
#define NATIONAL_DEX_MOSS 152
#define NATIONAL_DEX_MINIATURESNOOTWHACKER 153
#define NATIONAL_DEX_MAMMOTHSNOOTWHACKER 154
#define NATIONAL_DEX_TOYBORB 155
#define NATIONAL_DEX_BULBLORD 156
#define NATIONAL_DEX_PINCHIPEDE 157
#define NATIONAL_DEX_LARGEMOUTHWOLLYHOP 158
#define NATIONAL_DEX_TOYBLOWHOG 159
#define NATIONAL_DEX_TELESCOPINGPUMPHOG 160
#define NATIONAL_DEX_BEEB 161
#define NATIONAL_DEX_BLADEDBEEB 162
#define NATIONAL_DEX_STUDDEDBEEB 163
#define NATIONAL_DEX_FIREFLAPBULBORB 164
#define NATIONAL_DEX_ICEBLOWNDWEEVIL 165
#define NATIONAL_DEX_REDBUBBLIMP 166
#define NATIONAL_DEX_STARNACLE 167
#define NATIONAL_DEX_SPECTRALID 168
#define NATIONAL_DEX_BLUBBUG 169
#define NATIONAL_DEX_PUFFYBLUBBUG 170
#define NATIONAL_DEX_STUFFEDBELLBLOOM 171
#define NATIONAL_DEX_CENTIPARE 172
#define NATIONAL_DEX_ADULTCENTIPARE 173
#define NATIONAL_DEX_WATERYBLOWHOG 174
#define NATIONAL_DEX_SHEARFLEA 175
#define NATIONAL_DEX_GRABBIT 176
#define NATIONAL_DEX_COPPELLER 177
#define NATIONAL_DEX_MUGGONFLY 178
#define NATIONAL_DEX_ELECTRICCOTTONADE 179
#define NATIONAL_DEX_SOUL 180
#define NATIONAL_DEX_WADDLEPUS 181
#define NATIONAL_DEX_CRAMMEDWRAITH 182
#define NATIONAL_DEX_BERSERKLEECHHYDROE 183
#define NATIONAL_DEX_PEBBLEPITCHER 184
#define NATIONAL_DEX_ANCIENTSIREHOUND 185
#define NATIONAL_DEX_COURAGEREACTOR 186
#define NATIONAL_DEX_ASSEMBLEDCOURAGE 187
#define NATIONAL_DEX_REMEMBEREDOLDBUDDY 188
#define NATIONAL_DEX_BULBORBWITHAGUN 189
#define NATIONAL_DEX_KIRBY 190

#define NATIONAL_DEX_JUMBOBULBORB_MEGA 191
#define NATIONAL_DEX_TITANBLOWHOG_MEGA 192
#define NATIONAL_DEX_MASTERHOP_MEGA 193
#define NATIONAL_DEX_GLINTBEETLE_MEGA 194
#define NATIONAL_DEX_DIRIGIBUG_MEGA 195
#define NATIONAL_DEX_GIANTBREADBUG_MEGA 196
#define NATIONAL_DEX_SOVREIGNBULBLAX_MEGA 197
#define NATIONAL_DEX_DANDELFLY_MEGA 198
#define NATIONAL_DEX_PILEATEDSNAGRET_MEGA 199
#define NATIONAL_DEX_DESICCATEDSKITTERLEAF_MEGA 200
#define NATIONAL_DEX_ADULTBULBMIN_MEGAB 201
#define NATIONAL_DEX_ADULTBULBMIN_MEGAS 202
#define NATIONAL_DEX_MANATLEGS_MEGA 203
#define NATIONAL_DEX_VEHEAMOTHPHOSBAT_MEGA 204
#define NATIONAL_DEX_PYROCLASTICSLOOCH_MEGA 205
#define NATIONAL_DEX_GREATERSPOTTEDJELLYFLOAT_MEGA 206
#define NATIONAL_DEX_SNOWFLAKEFLUTTERTAIL_MEGA 207
#define NATIONAL_DEX_BOGSWALLOW_MEGA 208
#define NATIONAL_DEX_PUFFMIN_MEGA 209
#define NATIONAL_DEX_SCORCHCAKE_MEGA 210
#define NATIONAL_DEX_PUFFSTOOL_MEGA 211
#define NATIONAL_DEX_EMPRESSBULBLAX_MEGA 212
#define NATIONAL_DEX_MUCKERSKATE_MEGA 213
#define NATIONAL_DEX_GROOVYLONGLEGS_MEGA 214
#define NATIONAL_DEX_CRUSTEDRUMPUP_MEGA 215
#define NATIONAL_DEX_GATTLINGGROINK_MEGA 216
#define NATIONAL_DEX_ARMOREDMAWDAD_MEGA 217
#define NATIONAL_DEX_OATCHI_MEGAB 218
#define NATIONAL_DEX_OATCHI_MEGA 219
#define NATIONAL_DEX_QUAGGLEDMIRECLOPS_MEGA 220
#define NATIONAL_DEX_WHITEPIKMIN_MEGA 221
#define NATIONAL_DEX_BLUEPIKMIN_MEGA 222
#define NATIONAL_DEX_ROCKPIKMIN_MEGA 223
#define NATIONAL_DEX_YELLOWPIKMIN_MEGA 224
#define NATIONAL_DEX_WINGEDPIKMIN_MEGA 225
#define NATIONAL_DEX_REDPIKMIN_MEGA 226
#define NATIONAL_DEX_PURPLEPIKMIN_MEGA 227
#define NATIONAL_DEX_ICEPIKMIN_MEGA 228
#define NATIONAL_DEX_GLOWPIKMIN_MEGA 229
#define NATIONAL_DEX_MOSS_MEGAB 230
#define NATIONAL_DEX_MOSS_MEGA 231
#define NATIONAL_DEX_WATERYBLOWHOG_MEGA 232

#define FINAL_DEX_ENTRY NATIONAL_DEX_WATERYBLOWHOG_MEGA //Not +1 b/c used like this for some asm
#define NATIONAL_DEX_COUNT FINAL_DEX_ENTRY + 1
