#pragma once

#define POKEMON_NAME_LENGTH 10

#define SPECIES_NONE 0x0
#define SPECIES_BULBORBLARVA 0x1
#define SPECIES_BULBORB 0x2
#define SPECIES_JUMBOBULBORB 0x3
#define SPECIES_FIERYBLOWLET 0x4
#define SPECIES_FIERYBLOWHOG 0x5
#define SPECIES_TITANBLOWHOG 0x6
#define SPECIES_WOLPOLE 0x7
#define SPECIES_YELLOWWOLLYHOP 0x8
#define SPECIES_MASTERHOP 0x9
#define SPECIES_FLINTBEETLE 0xA
#define SPECIES_DOODLEBUG 0xB
#define SPECIES_GLINTBEETLE 0xC
#define SPECIES_SWOOPINGSNITCHBUG 0xD
#define SPECIES_BUMBLINGSNITCHBUG 0xE
#define SPECIES_DIRIGIBUG 0xF
#define SPECIES_SNOWBULBORB 0x10
#define SPECIES_DWARFFROSTYBULBORB 0x11
#define SPECIES_FROSTYBULBORB 0x12
#define SPECIES_CRUMBUG 0x13
#define SPECIES_BREADBUG 0x14
#define SPECIES_GIANTBREADBUG 0x15
#define SPECIES_EMPERORBULBLAX 0x16 
#define SPECIES_SOVREIGNBULBLAX 0x17 
#define SPECIES_DWARFBULBEAR 0x18
#define SPECIES_SPOTTYBULBEAR 0x19
#define SPECIES_HONEYWISP 0x1A
#define SPECIES_DANDELFLY 0x1B
#define SPECIES_DOWNYSNAGRET 0x1C
#define SPECIES_BURROWINGSNAGRET 0x1D
#define SPECIES_PILEATEDSNAGRET 0x1E
#define SPECIES_FEMALESHEARGRUB 0x1F
#define SPECIES_SWARMINGSHEARGRUB 0x20
#define SPECIES_MAMASHEARGRUB 0x21
#define SPECIES_MALESHEARGRUB 0x22
#define SPECIES_SHEARWIG 0x23
#define SPECIES_QUEENSHEARWIG 0x24
#define SPECIES_ARISTOCRABOFFSPRING 0x25
#define SPECIES_ARISTOCRAB 0x26
#define SPECIES_GOOLIX 0x27
#define SPECIES_FOOLIX 0x28
#define SPECIES_ARCTICCANNONLARVA 0x29
#define SPECIES_ARCTICCANNONBEETLE 0x2A
#define SPECIES_SKITTERLEAF 0x2B
#define SPECIES_DESICCATEDSKITTERLEAF 0x2C
#define SPECIES_ARMOREDCANNONLARVA 0x2D
#define SPECIES_ARMOREDCANNONBEETLE 0x2E
#define SPECIES_HORNEDCANNONBEETLE 0x2F
#define SPECIES_CREEPINGCHRYSANTHEMUM 0x30
#define SPECIES_STARTLESPORE 0x31
#define SPECIES_HERMITCRAWMAD 0x32
#define SPECIES_BUGEYEDCRAWMAD 0x33
#define SPECIES_DWARFBULBORB 0x34
#define SPECIES_DWARFORANGEBULBORB 0x35
#define SPECIES_BEADYLONGLEGS 0x36
#define SPECIES_RAGINGLONGLEGS 0x37
#define SPECIES_BALDYLONGLEGS 0x38
#define SPECIES_SHAGGYLONGLEGS 0x39
#define SPECIES_BULBMIN 0x3A
#define SPECIES_ADULTBULBMIN 0x3B
#define SPECIES_SCORNET 0x3C
#define SPECIES_SCORNETMAESTRO 0x3D 
#define SPECIES_BURROWNIT 0x3E
#define SPECIES_JOUSTMITE 0x3F 
#define SPECIES_FLIGHTYJOUSTMITE 0x40 
#define SPECIES_VOLATILEDWEEVIL 0x41
#define SPECIES_MANATLEGS 0x42
#define SPECIES_SKUTTERCHUCK 0x43 
#define SPECIES_CALCIFIEDCRUSHBLAT 0x44 
#define SPECIES_ARACHNODE 0x45
#define SPECIES_MOLDYDWARFBULBORB 0x46
#define SPECIES_MOLDYSLOOCH 0x47
#define SPECIES_TOXSTOOL 0x48
#define SPECIES_PHOSBAT 0x49
#define SPECIES_VEHEAMOTHPHOSBAT 0x4A
#define SPECIES_PUCKERINGBLINNOW 0x4B
#define SPECIES_SPUTTLEFISH 0x4C
#define SPECIES_PRICKLEPUFF 0x4D
#define SPECIES_UJADANI 0x4E 
#define SPECIES_MITITE 0x4F 
#define SPECIES_WITHERINGBLOWHOG 0x50 
#define SPECIES_PUFFYBLOWHOG 0x51
#define SPECIES_MINIATURESNOOTWHACKER 0x52 
#define SPECIES_MAMMOTHSNOOTWHACKER 0x53 
#define SPECIES_PYROCLASTICSLOOCH 0x54
#define SPECIES_LESSERSPOTTEDJELLYFLOAT 0x55
#define SPECIES_GREATERSPOTTEDJELLYFLOAT 0x56
#define SPECIES_TOADYBLOYSTER 0x57 
#define SPECIES_RANGINGBLOYSTER 0x58 
#define SPECIES_SNOWYBLOWHOG 0x59
#define SPECIES_BLIZZARDINGBLOWHOG 0x5A
#define SPECIES_GILDEMANDWEE 0x5B 
#define SPECIES_GILDEMANDER 0x5C 
#define SPECIES_WADDLEQUAFF 0x5D 
#define SPECIES_GRUBCHUCKER 0x5E 
#define SPECIES_PEARLYCLAMCLAMP 0x5F 
#define SPECIES_SUNQUISH 0x60
#define SPECIES_PROQUILLION 0x61
#define SPECIES_TUSKEDBLOWHOG 0x62 
#define SPECIES_SNOWFLAKEFLUTTERTAIL 0x63
#define SPECIES_BOGSWALLOW 0x64
#define SPECIES_PUFFMIN 0x65
#define SPECIES_WOLLYHOP 0x66
#define SPECIES_CHILLYHOP 0x67 
#define SPECIES_CUBONE 0x68 
#define SPECIES_SCORCHCAKE 0x69
#define SPECIES_WATERDUMPLE 0x6A
#define SPECIES_LONGWATERDUMPLE 0x6B
#define SPECIES_MOCKIWI 0x6C
#define SPECIES_CRESTEDMOCKIWI 0x6D 
#define SPECIES_ELONGATEDCRUSHBLAT 0x6E 
#define SPECIES_PUFFSTALK 0x6F 
#define SPECIES_PUFFSTOOL 0x70 
#define SPECIES_ANODEBEETLE 0x71 
#define SPECIES_EMPRESSBULBLAX 0x72 
#define SPECIES_SKEETERSKATE 0x73 
#define SPECIES_MUCKERSKATE 0x74 
#define SPECIES_GROOVYLONGLEGS 0x75 
#define SPECIES_CRUSTEDRUMPUP 0x76 
#define SPECIES_BEARDEDAMPRAT 0x77
#define SPECIES_FIERYBULBLAX 0x78 
#define SPECIES_GATTLINGGROINK 0x79
#define SPECIES_ARMURK 0x7A 
#define SPECIES_SEGMENTEDCRAWBSTER 0x7B 
#define SPECIES_ARMOREDMAWDAD 0x7C
#define SPECIES_SANDBELCHINGMEERSLUG 0x7D 
#define SPECIES_CLICKINGSLURKER 0x7E 
#define SPECIES_LURINGSLURKER 0x7F 
#define SPECIES_MEDUSALSLURKER 0x80 
#define SPECIES_PELLETPOSY 0x81
#define SPECIES_MASTERONION 0x82
#define SPECIES_OATCHI 0x83
#define SPECIES_QUAGGLEDMIRECLOPS 0x84
#define SPECIES_ALBINODWARFBULBORB 0x85
#define SPECIES_HAIRYBULBORB 0x86
#define SPECIES_WHIPTONGUEBULBORB 0x87
#define SPECIES_ORANGEBULBORB 0x88
#define SPECIES_WHITEPIKMIN 0x89
#define SPECIES_BLUEPIKMIN 0x8A
#define SPECIES_ROCKPIKMIN 0x8B
#define SPECIES_YELLOWPIKMIN 0x8C
#define SPECIES_ROCKPIKMIN 0x8D
#define SPECIES_REDPIKMIN 0x8E
#define SPECIES_PURPLEPIKMIN 0x8F
#define SPECIES_WATERWRAITH 0x90
#define SPECIES_TITANDWEEVIL 0x91
#define SPECIES_PLASMWRAITH 0x92
#define SPECIES_ICEPIKMIN 0x93
#define SPECIES_GLOWSEED 0x94
#define SPECIES_GLOWPIKMIN 0x95
#define SPECIES_SMOKYPROGG 0x96
#define SPECIES_MAMUTA 0x97
#define SPECIES_MOSS 0x98
#define SPECIES_TOYBORB 0x99
#define SPECIES_BULBLORD 0x9A
#define SPECIES_PINCHIPEDE 0x9B
#define SPECIES_LARGEMOUTHWOLLYHOP 0x9C
#define SPECIES_TOYBLOWHOG 0x9D
#define SPECIES_TELESCOPINGPUMPHOG 0x9E
#define SPECIES_BEEB 0x9F
#define SPECIES_BLADEDBEEB 0xA0
#define SPECIES_STUDDEDBEEB 0xA1
#define SPECIES_FIREFLAPBULBORB 0xA2
#define SPECIES_ICEBLOWNDWEEVIL 0xA3
#define SPECIES_SPECTRALID 0xA4
#define SPECIES_BLUBBUG 0xA5
#define SPECIES_PUFFYBLUBBUG 0xA6
#define SPECIES_STUFFEDBELLBLOOM 0xA7
#define SPECIES_CENTIPARE 0xA8
#define SPECIES_ADULTCENTIPARE 0xA9
#define SPECIES_WATERYBLOWHOG 0xAA
#define SPECIES_GRABBIT 0xAB
#define SPECIES_COPPELLER 0xAC
#define SPECIES_MUGGONFLY 0xAD
#define SPECIES_ELECTRICCOTTONADE 0xAE
#define SPECIES_WADDLEPUS 0xAF
#define SPECIES_CRAMMEDWRAITH 0xB0
#define SPECIES_BERSERKLEECHHYDROE 0xB1
#define SPECIES_PEBBLEPITCHER 0xB2
#define SPECIES_ANCIENTSIREHOUND 0xB3
#define SPECIES_COURAGEREACTOR 0xB4
#define SPECIES_ASSEMBLEDCOURAGE 0xB5
#define SPECIES_REMEMBEREDOLDBUDDY 0xB6
#define SPECIES_BULBORBWITHAGUN 0xB7
#define SPECIES_KIRBY 0xB8
#define SPECIES_SOUL 0xB9
#define SPECIES_PLACEHOLDERLARVA 0xBA
#define SPECIES_DEMO77 0xBB
#define SPECIES_USUBA 0xBC
#define SPECIES_KAKUREIMO 0xBD
#define SPECIES_PIKUTABE 0xBE
#define SPECIES_NAMAPONGASHI 0xBF
#define SPECIES_CHAPPYPROTO 0xC0

#define SPECIES_EGG 0xC1

#define SPECIES_GILDEMANDWEE_NOGOLD 0xC2	//091
#define SPECIES_GILDEMANDER_NOGOLD 0xC3		//092
#define SPECIES_BEARDEDAMPRAT_STATIC 0xC4	//119
#define SPECIES_REDPIKMIN_VETERAN 0xC5		//142
#define SPECIES_SMOKYPROGG_MASTER 0xC6		//150
#define SPECIES_SPECTRALID_RED 0xC7		//164
#define SPECIES_SPECTRALID_YELLOW 0xC8		//164
#define SPECIES_SPECTRALID_UNMARKED 0xC9	//164
#define SPECIES_SPECTRALID_UNMARKEDRED 0xCA	//164
#define SPECIES_SPECTRALID_UNMARKEDPURPLE 0xCB	//164
#define SPECIES_SPECTRALID_ELECTRIC 0xCC	//164
#define SPECIES_SPECTRALID_HEY0 0xCD		//164
#define SPECIES_SPECTRALID_HEY1 0xCE		//164
#define SPECIES_ANCIENTSIREHOUND_ICE 0xCF	//179
#define SPECIES_ANCIENTSIREHOUND_ELECTRIC 0xD0	//179
#define SPECIES_ANCIENTSIREHOUND_FIRE 0xD1	//179
#define SPECIES_ANCIENTSIREHOUND_GLOOM 0xD2	//179
#define SPECIES_KIRBY_FLYING 0xD3		//184
#define SPECIES_KIRBY_GRASS 0xD4		//184
#define SPECIES_KIRBY_BUG 0xD5			//184
#define SPECIES_KIRBY_POISON 0xD6		//184
#define SPECIES_KIRBY_WATER 0xD7		//184
#define SPECIES_KIRBY_ICE 0xD8			//184
#define SPECIES_KIRBY_FIRE 0xD9			//184
#define SPECIES_KIRBY_ELECTRIC 0xDA		//184
#define SPECIES_KIRBY_FIGHTING 0xDB		//184
#define SPECIES_KIRBY_ROCK 0xDC			//184
#define SPECIES_KIRBY_GROUND 0xDD		//184
#define SPECIES_KIRBY_PSYCHIC 0xDE		//184
#define SPECIES_KIRBY_GHOST 0xDF		//184
#define SPECIES_KIRBY_DRAGON 0xE0		//184
#define SPECIES_KIRBY_DARK 0xE1			//184
#define SPECIES_KIRBY_STEEL 0xE2		//184
#define SPECIES_KIRBY_FAIRY 0xE3		//184
#define SPECIES_SOUL_RED 0xE4			//185
#define SPECIES_SOUL_YELLOW 0xE5		//185
#define SPECIES_SOUL_BLUE 0xE6			//185
#define SPECIES_SOUL_PURPLE 0xE7		//185
#define SPECIES_SOUL_WHITE 0xE8			//185
#define SPECIES_SOUL_ROCK 0xE9			//185
#define SPECIES_SOUL_WINGED 0xEA		//185
#define SPECIES_SOUL_ICE 0xEB			//185

#define SPECIES_JUMBOBULBORB_MEGA 0xEC		//003
#define SPECIES_TITANBLOWHOG_MEGA 0xED		//006
#define SPECIES_MASTERHOP_MEGA 0xEE		//009
#define SPECIES_GLINTBEETLE_MEGA 0xEF		//012
#define SPECIES_GIANTBREADBUG_MEGA 0xF0		//021
#define SPECIES_SOVREIGNBULBLAX_MEGA 0xF1	//023
#define SPECIES_DANDELFLY_MEGA 0xF2		//027
#define SPECIES_PILEATEDSNAGRET_MEGA 0xF3	//030
#define SPECIES_ADULTBULBMIN_MEGAB 0xF4		//059
#define SPECIES_ADULTBULBMIN_MEGAS 0xF5		//059
#define SPECIES_MANATLEGS_MEGA 0xF6		//066
#define SPECIES_PUFFMIN_MEGA 0xF7		//101
#define SPECIES_EMPRESSBULBLAX_MEGA 0xF8	//114
#define SPECIES_ARMOREDMAWDAD_MEGA 0xF9		//124
#define SPECIES_OATCHI_MEGA 0xFA		//131
#define SPECIES_QUAGGLEDMIRECLOPS_MEGA 0xFB	//132
#define SPECIES_WHITEPIKMIN_MEGA 0xFC		//137
#define SPECIES_BLUEPIKMIN_MEGA 0xFD		//138
#define SPECIES_ROCKPIKMIN_MEGA 0xFE		//139
#define SPECIES_YELLOWPIKMIN_MEGA 0xFF		//140
#define SPECIES_WINGEDPIKMIN_MEGA 0x100		//141
#define SPECIES_REDPIKMIN_MEGA 0x101		//142
#define SPECIES_PURPLEPIKMIN_MEGA 0x102		//143
#define SPECIES_ICEPIKMIN_MEGA 0x103		//147
#define SPECIES_GLOWPIKMIN_MEGA 0x104		//149
#define SPECIES_MOSS_MEGA 0x105			//152

#define NUM_SPECIES (SPECIES_MOSS_MEGA + 1)
